------------------------------------------------------------------------------------------------------------------------
-- TASK_3_EXCEPTIONS | Обработка исключений
------------------------------------------------------------------------------------------------------------------------
Что плохого в этом коде?
```
public IQueryable<T> GetAll()
{
	try
	{
		return dbSet.AsQueryable();
	}
	catch (Exception ex)
	{
		throw new Exception(ex.Message);
	}
}
```

Замечания по коду:
1. Потеряли `ex.InnerException`.
2. Пропущено логирование. Можно собрать все вложенные `Message`, либо сериализовать весь объект `ex` в XML. Места будет занимать больше, но поиск ошибок будет удобнее.
3. Генерацию Exception необходимо обернуть в асинхронную нотификацию пользователя.
4. По ситуации, можно добавить атрибуты в метод, пробросить в лог: 
`public IQueryable<T> GetAll([CallerFilePath] string filePath = "", [CallerLineNumber] int lineNumber = 0, [CallerMemberName] string memberName = "")`
